version: '0.2'
phases:
  pre_build:
    commands:
      - 'aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com'
  build:
    commands:
      - 'docker build --cache-from $ECR_REPOSITORY_URI:$IMAGE_TAG --build-arg PHP_TIMEZONE=$PHP_TIMEZONE --build-arg LANG_S3_URI=$LANG_S3_URI --build-arg REDCAP_S3_URI=$REDCAP_S3_URI --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg PORT=$PORT --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t $ECR_REPOSITORY_URI:latest .'
  post_build:
    commands:
      - 'docker push $ECR_REPOSITORY_URI:$IMAGE_TAG'
      - 'docker push $ECR_REPOSITORY_URI:latest'
